#!/bin/sh

UBUNTU_VERSION=20.04
PROTOC_VERSION=3.13.0
NODE_VERSION=14.15
TS_PROTOC_GEN_VERSION=0.13.0
GRPC_TOOLS_VERSION=1.9.1
GRPC_WEB_VERSION=1.2.1

docker build \
--build-arg UBUNTU_VERSION=${UBUNTU_VERSION} \
--build-arg PROTOC_VERSION=${PROTOC_VERSION} \
--build-arg NODE_VERSION=${NODE_VERSION} \
--build-arg TS_PROTOC_GEN_VERSION=${TS_PROTOC_GEN_VERSION} \
--build-arg GRPC_TOOLS_VERSION=${GRPC_TOOLS_VERSION} \
--build-arg GRPC_WEB_VERSION=${GRPC_WEB_VERSION} \
${@} .